# Generated by Django 3.1.6 on 2021-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_devis', models.DateTimeField(auto_now_add=True)),
                ('firstname', models.CharField(max_length=100, unique=True)),
                ('lastname', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('website', models.URLField()),
                ('statut', models.CharField(max_length=255, verbose_name='state')),
                ('description', models.TextField()),
            ],
        ),
    ]
